spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://kelprograms:kelprograms@localhost:27017/fitnessactivity?authSource=admin
      database: fitnessactivity
server:
  port: 8082



