services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"         # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: kelprograms     # Root username
      MONGO_INITDB_ROOT_PASSWORD: kelprograms    # Root password
    volumes:
      - mongo-data:/data/db     # Persist data outside container

volumes:
  mongo-data:
    driver: local